# Generated by Django 4.0.5 on 2022-06-24 20:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_alter_store_is_active'),
        ('stock', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='inventory',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='inventory.store'),
        ),
    ]
