# Generated by Django 4.1 on 2022-08-10 16:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_alter_organization_owner_alter_user_name'),
        ('stock', '0004_alter_order_bill'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Bill',
            new_name='Invoice',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='bill',
            new_name='invoice',
        ),
    ]
