# Generated by Django 4.1.7 on 2023-05-27 23:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0013_category_is_featured'),
        ('dinner', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dinnerorder',
            name='owner',
            field=models.CharField(default=1, max_length=45),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dinnerorder',
            name='products',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='inventory.product'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dinnerorder',
            name='subtotal',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dinnerorder',
            name='tips',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='table',
            name='customers',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='table',
            name='isActive',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='table',
            name='number',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='table',
            name='orders',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dinner.dinnerorder'),
        ),
        migrations.AddField(
            model_name='table',
            name='total',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
