# Generated by Django 4.1.7 on 2023-05-28 00:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dinner', '0002_dinnerorder_owner_dinnerorder_products_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DinnerProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('description', models.TextField()),
                ('price', models.IntegerField()),
                ('category', models.CharField(max_length=40)),
                ('image', models.CharField(max_length=300)),
            ],
        ),
        migrations.AlterField(
            model_name='dinnerorder',
            name='products',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dinner.dinnerproduct'),
        ),
    ]
