# Generated by Django 4.1.7 on 2023-05-28 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dinner', '0003_dinnerproduct_alter_dinnerorder_products'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dinnerproduct',
            name='price',
            field=models.FloatField(),
        ),
    ]
