# Generated by Django 4.1.7 on 2023-05-28 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dinner', '0004_alter_dinnerproduct_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dinnerorder',
            name='subtotal',
            field=models.FloatField(),
        ),
    ]
