# Generated by Django 4.1.7 on 2023-05-28 02:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dinner', '0005_alter_dinnerorder_subtotal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dinnerorder',
            name='products',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dinner.dinnerproduct'),
        ),
    ]
