# Generated by Django 3.2.6 on 2021-08-12 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('category', models.CharField(max_length=64)),
                ('stock', models.IntegerField()),
                ('unit', models.CharField(max_length=32)),
                ('is_active', models.CharField(max_length=16)),
            ],
        ),
    ]
