# Generated by Django 3.2.6 on 2021-08-12 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_rename_inventory_store'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='is_active',
            field=models.CharField(default='active', max_length=16),
        ),
    ]
