# Generated by Django 4.0.6 on 2022-08-03 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_user_email_alter_user_phone_organization'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='phone',
            field=models.PositiveBigIntegerField(unique=True),
        ),
    ]
