# Generated by Django 4.1 on 2022-08-10 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_user_identifer'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='id_type',
            field=models.CharField(default='CC', max_length=10),
        ),
    ]
