# Generated by Django 4.1 on 2022-08-20 22:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_rename_identifer_user_identifier'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='organization',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='user.organization'),
        ),
    ]
