# Generated by Django 4.1 on 2022-08-20 23:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0011_staff_organization'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='organization',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='user.organization'),
        ),
    ]
