# Generated by Django 4.1 on 2022-08-20 23:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0012_alter_staff_organization'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staff',
            name='organization',
        ),
    ]
