# Generated by Django 4.1 on 2022-08-22 17:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0013_remove_staff_organization'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='organization',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='user.organization'),
        ),
    ]
