# Generated by Django 4.1.7 on 2023-03-10 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0015_alter_user_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='logo',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
